name: Docker Image CI

on:
  workflow_dispatch: # 手动触发

env:
  BUILD_VERSION: latest
  IMAGE_NAME: ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NAMESPACE }}/thingsboard

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查磁盘空间
        run: df -h
